# Generated by Django 5.0.6 on 2024-06-13 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='linkedin_link',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='normal_link',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='twitter_link',
        ),
    ]
